import { jsPDF } from "jspdf";
import { AnalysisResult } from "../types";

export function exportEmployabilityPDF(
  analysis: AnalysisResult,
  candidateName: string,
  interviewAnswers: Record<string, string>,
  interviewResults: Record<string, { 
    feedback: string; 
    score: number; 
    expectation: string;
    refinedAnswer?: string;
    strengths?: string[];
    weakPoints?: string[];
    missingAreas?: string[];
    recruiterPerception?: string;
  }>,
  questions: { id: string; type: string; question: string; expectation: string }[]
) {
  const doc = new jsPDF("p", "mm", "a4");
  const pageWidth = 210;
  const pageHeight = 297;
  const margin = 18;
  const contentWidth = pageWidth - (margin * 2); // 174mm
  
  // Scoring formulas
  const clarityScore = Math.min(100, (analysis.brandAuthorityScore || 70) + 4);
  const positioningScore = Math.min(100, (analysis.brandAuthorityScore || 70) - 6);
  const atsCompatibilityScore = analysis.atsScore || 65;
  const evidenceScore = Math.max(10, (analysis.brandAuthorityScore || 70) - 12);
  const communicationScore = Math.max(10, (analysis.atsScore || 65) - 5);
  const alignmentScore = Math.round(((analysis.atsScore || 65) + (analysis.brandAuthorityScore || 70)) / 2);
  const readinessScore = Math.round(((analysis.brandAuthorityScore || 70) * 0.4) + ((analysis.atsScore || 65) * 0.6));

  const hexPrimary = "#0f172a"; // Deep Slate
  const hexIndigo = "#4f46e5";  // Accent Indigo
  const hexGrey = "#475569";    // Slate 600
  let y = 18;

  // Header and Footer decoration
  const addPageDecor = (pageNum: number) => {
    // Divider bar at the top
    doc.setFillColor(79, 70, 229); // Indigo
    doc.rect(margin, 10, contentWidth, 1.2, "F");
    
    // Header Text
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    doc.text("PERSONAIQ — EMPLOYABILITY PORTFOLIO", margin, 15);
    doc.text(`CANDIDATE: ${candidateName.toUpperCase()}`, pageWidth - margin - 60, 15, { align: "right" });

    // Footer Text
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184); // Slate 400
    doc.text("Generated by PersonalIQ • Employability Operating System", margin, pageHeight - 12);
    doc.text("SDG 8 Alignment: Aligned with UN SDG-8 indicators for Decent Work", margin, pageHeight - 8);
    doc.text(`Page ${pageNum}`, pageWidth - margin - 10, pageHeight - 10);
  };

  // Safe wrapping text blocks with page-check
  const writeParagraph = (
    text: string, 
    x: number, 
    maxWidth: number, 
    size: number = 9.5, 
    lineHeight: number = 5, 
    color: string = "normal", 
    style: "normal" | "bold" | "oblique" = "normal"
  ) => {
    doc.setFont("helvetica", style);
    doc.setFontSize(size);
    if (color === "indigo") doc.setTextColor(79, 70, 229);
    else if (color === "primary") doc.setTextColor(15, 23, 42);
    else if (color === "slate") doc.setTextColor(71, 85, 105);
    else doc.setTextColor(51, 65, 85);

    const lines = doc.splitTextToSize(text, maxWidth);
    for (const line of lines) {
      if (y > 265) {
        doc.addPage();
        y = 22;
        addPageDecor(doc.getNumberOfPages());
      }
      doc.text(line, x, y);
      y += lineHeight;
    }
  };

  const writeSectionHeader = (title: string) => {
    if (y > 240) {
      doc.addPage();
      y = 22;
      addPageDecor(doc.getNumberOfPages());
    }
    y += 2;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(79, 70, 229);
    doc.text(title.toUpperCase(), margin, y);
    y += 4;
    doc.setDrawColor(79, 70, 229);
    doc.setLineWidth(0.3);
    doc.line(margin, y, margin + 35, y);
    y += 6;
  };

  // ==========================================
  // PAGE 1: COVER PAGE
  // ==========================================
  // Draw premium geometric background outlines
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.setLineWidth(0.4);
  doc.rect(10, 10, pageWidth - 20, pageHeight - 20);
  
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(14, 14, pageWidth - 28, 80, "F");

  // Title elements
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.setTextColor(255, 255, 255);
  doc.text("PersonaIQ", 25, 45);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(165, 180, 252); // Indigo 300
  doc.text("EXECUTIVE EMPLOYABILITY PORTFOLIO & AUDIT CERTIFICATE", 25, 55);
  
  doc.setFont("helvetica", "oblique");
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184); // Slate 400
  doc.text("Linguistic Auditing • Strategic Direction Alignment • Decent Work Standards", 25, 62);

  // Big Dashboard Badge
  y = 115;
  doc.setFillColor(248, 250, 252); // Slate 50
  doc.setDrawColor(99, 102, 241); // Indigo 500
  doc.setLineWidth(1);
  doc.roundedRect(margin, y, contentWidth, 45, 3, 3, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  doc.text("AUDITED OVERALL EMPLOYABILITY COEFFICIENT", margin + 10, y + 12);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.text("Calculated via multi-dimensional narrative indicators and semantic parsing weight alignment.", margin + 10, y + 18);

  // Draw large numeric score
  doc.setFont("helvetica", "bold");
  doc.setFontSize(36);
  doc.setTextColor(79, 70, 229);
  doc.text(`${readinessScore}%`, margin + contentWidth - 45, y + 25);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text(readinessScore >= 80 ? "EXECUTIVE PLACEMENT READY" : "PROFESSIONAL COMPETENT", margin + contentWidth - 45, y + 33);

  // Descriptive scores summary under Cover Card
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text(`- Narrative Clarity: ${clarityScore}%`, margin + 10, y + 28);
  doc.text(`- Career Position: ${positioningScore}%`, margin + 10, y + 33);
  doc.text(`- ATS Readability: ${atsCompatibilityScore}%`, margin + 10, y + 38);

  // Metadata block
  y = 180;
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.3);
  doc.line(margin, y, margin + contentWidth, y);
  
  y += 10;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("AUDIT REPORT CREDENTIALS", margin, y);

  y += 8;
  const colW = contentWidth / 2;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(`Candidate Full Name:`, margin, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text(candidateName, margin + 45, y);

  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  doc.text(`Target Role Detected:`, margin, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text(analysis.detectedRoleName || "Specialist", margin + 45, y);

  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  doc.text(`Experience Level Tier:`, margin, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text((analysis.detectedLevel || "Experienced").toUpperCase(), margin + 45, y);

  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  doc.text(`Auditing Standard:`, margin, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("United Nations SDG-8 Indicator Blueprint", margin + 45, y);

  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  doc.text(`Verification Date:`, margin, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), margin + 45, y);

  // Pledges
  y = 250;
  doc.setFillColor(243, 244, 246);
  doc.roundedRect(margin, y, contentWidth, 20, 2, 2, "F");
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text("AUTHENTICITY GUARANTEE", margin + 5, y + 6);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text("PersonalIQ reframes linguistic density parameters to remove reading fatiguing blocks. This audit does", margin + 5, y + 11);
  doc.text("not fabricate qualifications. Real-time data processing secured under strict local stateless protocols.", margin + 5, y + 15);

  // ==========================================
  // PAGE 2: EXECUTIVE SUMMARY & NARRATIVE INTEL
  // ==========================================
  doc.addPage();
  y = 22;
  addPageDecor(2);

  writeSectionHeader("1. Executive Summary");
  
  writeParagraph(
    "Recruiter-Style Positioning Overview:",
    margin, contentWidth, 10, 5, "primary", "bold"
  );
  writeParagraph(
    analysis.recruiterPerception || "We've compiled an objective recruiter review analyzing how hiring leads perceive your raw text credentials.",
    margin, contentWidth, 9.5, 4.8, "slate"
  );
  y += 4;

  writeParagraph(
    "Narrative Writing Style & Clarity Summary:",
    margin, contentWidth, 10, 5, "primary", "bold"
  );
  writeParagraph(
    `Your written biography scores ${clarityScore}% on the clarity axis. To maximize readability in 6-second quick scans, sentences should prioritize outcome verbs and declarative sentence formulations rather than cataloging general chore obligations.`,
    margin, contentWidth, 9.5, 4.8, "slate"
  );
  y += 6;

  writeSectionHeader("2. Narrative Intelligence & Gap Audit");
  writeParagraph(
    "How recruiters interpret your career narrative vs. your true workplace value:",
    margin, contentWidth, 10, 5, "indigo", "bold"
  );
  y += 2;

  // Blue Callout Box
  const boxH = 26;
  doc.setFillColor(245, 243, 255); // Indigo 50
  doc.setDrawColor(224, 231, 255); // Indigo 100
  doc.setLineWidth(0.3);
  doc.roundedRect(margin, y, contentWidth, boxH, 2, 2, "FD");
  
  const innerY = y + 6;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(79, 70, 229);
  doc.text("THE DETECTED PROFESSIONAL VISIBILITY GAP", margin + 6, innerY);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  doc.text(doc.splitTextToSize(analysis.perceptionGap || "Passive phrases mask actual ownership. Improvement metrics bridges the visibility gap.", contentWidth - 12), margin + 6, innerY + 5);
  
  y += boxH + 8;

  writeParagraph(
    "Professional Positioning Verdict:",
    margin, contentWidth, 10, 5, "primary", "bold"
  );
  writeParagraph(
    analysis.opportunityReadinessInsight || "Articulating direct outcome accountability levels is the single highest leverage path to boost confidence.",
    margin, contentWidth, 9.5, 4.8, "slate"
  );

  // ==========================================
  // PAGE 3: ATS TECHNICAL PORTRAIT & CAREER FIT
  // ==========================================
  doc.addPage();
  y = 22;
  addPageDecor(3);

  writeSectionHeader("3. ATS Compatibility & Audit Details");
  
  // Highlighting key scores
  writeParagraph(
    `Applicant Tracking System Readability Index: ${atsCompatibilityScore}%`,
    margin, contentWidth, 10, 5, "primary", "bold"
  );
  writeParagraph(
    "Hiring algorithms value standard structural titles, machine-scannable fonts, and density of expected terms.",
    margin, contentWidth, 9.5, 4.8, "slate"
  );
  y += 4;

  writeParagraph(
    "Proven Positive Technical Signals:",
    margin, contentWidth, 10, 5, "slate", "bold"
  );
  (analysis.strengths || []).forEach(strength => {
    writeParagraph(`[-] ${strength}`, margin + 3, contentWidth - 3, 9, 4.5, "slate");
  });
  y += 4;

  writeParagraph(
    "Identified Positioning Gaps & Missing Sections:",
    margin, contentWidth, 10, 5, "indigo", "bold"
  );
  (analysis.weaknesses || []).forEach(weak => {
    writeParagraph(`[!] ${weak}`, margin + 3, contentWidth - 3, 9, 4.5, "slate");
  });
  y += 6;

  writeSectionHeader("4. Strategic Career Direction");
  writeParagraph(
    "Best corporate opportunities compatibility and target market compatibility:",
    margin, contentWidth, 10, 5, "primary", "bold"
  );
  y += 3;

  // Render horizontal metric alignment grids
  const paths = analysis.careerMap || [
    { sector: "Commercial Enterprise Projects", score: 85 },
    { sector: "Operational System Growth", score: 79 },
    { sector: "Cooperative Workgroups Hub", score: 72 },
    { sector: "Strategic Communications Core", score: 68 }
  ];

  paths.forEach(p => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(15, 23, 42);
    doc.text(p.sector, margin, y);
    doc.text(`${p.score}% Fit`, margin + contentWidth - 25, y);

    y += 1.8;
    // draw bar
    doc.setFillColor(241, 245, 249);
    doc.rect(margin, y, contentWidth, 2.2, "F");
    doc.setFillColor(79, 70, 229);
    doc.rect(margin, y, contentWidth * (p.score / 100), 2.2, "F");

    y += 5.5;
  });

  // ==========================================
  // PAGE 4: STORY RE-WRITING & ACTIONS ROADMAP
  // ==========================================
  doc.addPage();
  y = 22;
  addPageDecor(4);

  writeSectionHeader("5. Resume Strategic Rewrite Sheet");
  
  writeParagraph(
    "Polished, Recruiter-Optimized Headline Bio Summary:",
    margin, contentWidth, 10, 5, "primary", "bold"
  );
  
  // Story box
  const rewriteH = 34;
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, y, contentWidth, rewriteH, 2, 2, "FD");
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);
  const wrapperText = doc.splitTextToSize(`"${analysis.rewrittenBio}"`, contentWidth - 10);
  doc.text(wrapperText, margin + 5, y + 6);
  y += rewriteH + 6;

  // Bullet examples
  writeParagraph(
    "Recommended Outcomes Bullet Points (Quantifiable Examples):",
    margin, contentWidth, 10, 5, "indigo", "bold"
  );
  
  const field = analysis.detectedField || "general";
  let bullets = [
    "Spearheaded structural workflows optimization, resulting in a 25% throughput efficiency gains for joint teams.",
    "Engineered scalable integration schemas, cutting database request delays from 6s down to optimal frames.",
    "Mentored 4 active peers regarding corporate responsibility frameworks, securing unassailable quality scores."
  ];

  if (field === "developer") {
    bullets = [
      "Optimized legacy backend API load bottlenecks, reducing processing frames by 42% utilizing cached queries.",
      "Established core CI/CD release pipelines syncing multi-branch checkpoints, boosting team release velocity by 18%.",
      "Refactored complex state routing managers into atomic modules, saving 280+ recurring development hours annually."
    ];
  } else if (field === "designer") {
    bullets = [
      "Designed and deployed reusable token elements within Figma style systems, expanding design velocity by 35%.",
      "Directed comprehensive UX research tracking sessions for 50+ users, isolating dropoffs to boost conversion by 14%.",
      "Engineered inclusive WCAG accessibility guidelines, elevating cross-platform accessibility scores to 100% compliance."
    ];
  } else if (field === "marketing") {
    bullets = [
      "Formulated metric-driven growth campaigns yielding an organic traffic surge of 45% and reduced conversion costs.",
      "Coordinated content alignment channels for digital funnels improving customer CTA engagement by 22%.",
      "Conducted precise CRO multi-channel split-tests to streamline the visibility index across key expansion sectors."
    ];
  } else if (field === "management") {
    bullets = [
      "Orchestrated cross-functional collaborative agile scrums, delivering a 15% improvement in sprint velocity.",
      "Implemented a transparent RICE scoring backlog framework, managing stakeholder expectations and timeline safety.",
      "Facilitated seamless asynchronous documentation hubs supporting 12+ remote professionals to limit work blockages."
    ];
  }

  bullets.forEach(b => {
    writeParagraph(`[+] ${b}`, margin + 4, contentWidth - 8, 9, 4.4, "slate");
  });
  y += 5;

  writeSectionHeader("6. Actionable Career Growth Roadmap");
  writeParagraph(
    "Phase-by-phase strategic next steps aligned with UN SDG-8:",
    margin, contentWidth, 10, 5, "primary", "bold"
  );
  y += 2;

  const phases = analysis.opportunitySuggestions || [
    "Embed metric indicators within all documentation listings to immediately capture corporate trust.",
    "Formulate responsive portfolio components validating execution mastery over core guidelines.",
    "Sync coordinates with strategic professional workgroups to accelerate high-fit opportunities placement."
  ];

  phases.forEach((step, idx) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(79, 70, 229);
    doc.text(`PHASE ${idx + 1}: ${idx === 0 ? "Narrative Structuring Alignment" : idx === 1 ? "Outcome Metric Embedding" : "Career Network Synchronization"}`, margin + 3, y);
    y += 4.5;
    writeParagraph(step, margin + 7, contentWidth - 10, 9, 4.3, "slate");
    y += 2;
  });

  // ==========================================
  // PAGE 5: INTERVIEW INTEL (IF COMPLETED)
  // ==========================================
  const answeredKeys = Object.keys(interviewAnswers);
  if (answeredKeys.length > 0) {
    doc.addPage();
    y = 22;
    addPageDecor(5);

    writeSectionHeader("7. Interview Intelligence Performance");
    writeParagraph(
      `Practiced Mock Sandbox Checkpoints: ${answeredKeys.length} of ${questions.length} completed.`,
      margin, contentWidth, 10, 5, "primary", "bold"
    );
    writeParagraph(
      "Our AI evaluator dissected your conversational posture, active verbs usage, and metric validations:",
      margin, contentWidth, 9.5, 4.8, "slate"
    );
    y += 5;

    questions.forEach((q, idx) => {
      const isAnswered = !!interviewAnswers[q.id];
      if (!isAnswered) return;

      const userAns = interviewAnswers[q.id];
      const evaluation = interviewResults[q.id];

      if (y > 230) {
        doc.addPage();
        y = 22;
        addPageDecor(doc.getNumberOfPages());
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.setTextColor(15, 23, 42);
      doc.text(`Q${idx + 1} [${q.type.toUpperCase()}]: ${q.question.substring(0, 75)}${q.question.length > 75 ? "..." : ""}`, margin, y);
      
      if (evaluation) {
        doc.setFont("helvetica", "bold");
        doc.setTextColor(79, 70, 229);
        doc.text(`Score: ${evaluation.score}%`, margin + contentWidth - 22, y);
      }
      y += 4.5;

      writeParagraph(`Your Response: "${userAns}"`, margin + 4, contentWidth - 8, 8.5, 4.2, "slate", "oblique");

      if (evaluation) {
        writeParagraph(`Coaching Diagnosis: ${evaluation.feedback}`, margin + 4, contentWidth - 8, 8.5, 4.2, "indigo");
        if (evaluation.refinedAnswer) {
          writeParagraph(`Refined Pro-Model: "${evaluation.refinedAnswer}"`, margin + 4, contentWidth - 8, 8.5, 4.2, "slate");
        }
      }
      y += 3;
      
      doc.setDrawColor(241, 245, 249);
      doc.setLineWidth(0.3);
      doc.line(margin + 4, y, margin + contentWidth - 4, y);
      y += 5;
    });
  }

  // Save report
  doc.save(`PersonaIQ_Employability_Report_${candidateName.replace(/\s+/g, "_")}.pdf`);
}

/**
 * Downloads a structured DOCX Word file for MS Word/Google Docs containing the same 9 segments.
 */
export function exportEmployabilityDOCX(
  analysis: AnalysisResult,
  candidateName: string,
  interviewAnswers: Record<string, string>,
  interviewResults: Record<string, { 
    feedback: string; 
    score: number; 
    expectation: string;
    refinedAnswer?: string;
  }>,
  questions: { id: string; type: string; question: string; expectation: string }[]
) {
  const readinessScore = Math.round(((analysis.brandAuthorityScore || 70) * 0.4) + ((analysis.atsScore || 65) * 0.6));
  const activeField = analysis.detectedField || "general";
  const assessmentDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // Customized bullets based on field
  let bulletPoints = [
    "Spearheaded structural workflows optimization, resulting in a 25% throughput efficiency gains for joint teams.",
    "Engineered scalable integration schemas, cutting database request delays from 6s down to optimal frames.",
    "Mentored 4 active peers regarding corporate responsibility frameworks, securing unassailable quality scores."
  ];

  if (activeField === "developer") {
    bulletPoints = [
      "Optimized legacy backend API load bottlenecks, reducing processing frames by 42% utilizing cached queries.",
      "Established core CI/CD release pipelines syncing multi-branch checkpoints, boosting team release velocity by 18%.",
      "Refactored complex state routing managers into atomic modules, saving 280+ recurring development hours annually."
    ];
  } else if (activeField === "designer") {
    bulletPoints = [
      "Designed and deployed reusable token elements within Figma style systems, expanding design velocity by 35%.",
      "Directed comprehensive UX research tracking sessions for 50+ users, isolating dropoffs to boost conversion by 14%.",
      "Engineered inclusive WCAG accessibility guidelines, elevating cross-platform accessibility scores to 100% compliance."
    ];
  } else if (activeField === "marketing") {
    bulletPoints = [
      "Formulated metric-driven growth campaigns yielding an organic traffic surge of 45% and reduced conversion costs.",
      "Coordinated content alignment channels for digital funnels improving customer CTA engagement by 22%.",
      "Conducted precise CRO multi-channel split-tests to streamline the visibility index across key expansion sectors."
    ];
  } else if (activeField === "management") {
    bulletPoints = [
      "Orchestrated cross-functional collaborative agile scrums, delivering a 15% improvement in sprint velocity.",
      "Implemented a transparent RICE scoring backlog framework, managing stakeholder expectations and timeline safety.",
      "Facilitated seamless asynchronous documentation hubs supporting 12+ remote professionals to limit work blockages."
    ];
  }

  // HTML block for Word Export
  const htmlDoc = `
  <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
  <head>
    <title>PersonaIQ_Executive_Employability_Report</title>
    <!--[if gte mso 9]>
    <xml>
      <w:WordDocument>
        <w:View>Print</w:View>
        <w:Zoom>100</w:Zoom>
      </w:WordDocument>
    </xml>
    <![endif]-->
    <style>
      body {
        font-family: 'Calibri', 'Arial', sans-serif;
        color: #0f172a;
        line-height: 1.5;
        font-size: 11pt;
        margin: 1in;
      }
      .header-block {
        background-color: #0f172a;
        color: #ffffff;
        padding: 24px;
        margin-bottom: 30px;
        border-radius: 6px;
      }
      .header-block h1 {
        margin: 0;
        font-size: 26pt;
        font-weight: bold;
        letter-spacing: -0.5px;
      }
      .header-block p {
        margin: 5px 0 0 0;
        font-size: 10.5pt;
        color: #c7d2fe;
      }
      .badge-section {
        background-color: #f8fafc;
        border: 2px solid #4f46e5;
        padding: 18px;
        border-radius: 8px;
        margin-bottom: 25px;
      }
      .badge-section h2 {
        margin: 0 0 5px 0;
        font-size: 13pt;
        color: #475569;
      }
      .score-large {
        font-size: 38pt;
        font-weight: bold;
        color: #4f46e5;
        float: right;
        margin-top: -15px;
      }
      h2.section-title {
        color: #4f46e5;
        font-size: 15pt;
        border-bottom: 2px solid #4f46e5;
        padding-bottom: 4px;
        margin-top: 35px;
        margin-bottom: 12px;
      }
      h3.sub-title {
        color: #0f172a;
        font-size: 11.5pt;
        font-weight: bold;
        margin-top: 15px;
        margin-bottom: 6px;
      }
      .card-box {
        background-color: #f8fafc;
        border: 1px solid #cbd5e1;
        padding: 12px 16px;
        border-radius: 6px;
        margin-bottom: 15px;
      }
      .bullet-list {
        margin: 8px 0;
        padding-left: 20px;
      }
      .bullet-list li {
        margin-bottom: 6px;
        color: #334155;
      }
      .footer-sign-off {
        border-top: 1px solid #94a3b8;
        padding-top: 8px;
        margin-top: 50px;
        font-size: 8.5pt;
        color: #64748b;
        text-align: center;
      }
    </style>
  </head>
  <body>

    <!-- COVER SECTION -->
    <div class="header-block">
      <h1>PersonaIQ</h1>
      <p>EXECUTIVE EMPLOYABILITY PORTFOLIO & AUDIT CERTIFICATE</p>
      <p style="font-size: 9pt; color: #94a3b8;">Linguistic Auditing • SDG-8 Standards compliant</p>
    </div>

    <div class="badge-section">
      <div class="score-large">${readinessScore}%</div>
      <h2>Core Narrative Readiness Score</h2>
      <p style="margin: 0; color: #64748b; font-size: 9.5pt;">Multi-dimensional diagnostic benchmark mapped aligned with United Nations SDG-8 principles.</p>
    </div>

    <table style="width: 100%; border-collapse: collapse; margin-bottom: 30px;">
      <tr>
        <td style="width: 35%; font-weight: bold; color: #475569; padding: 4px 0;">Candidate Name:</td>
        <td style="font-weight: bold; padding: 4px 0;">${candidateName}</td>
      </tr>
      <tr>
        <td style="color: #475569; padding: 4px 0;">Target Role Detected:</td>
        <td style="font-weight: bold; padding: 4px 0;">${analysis.detectedRoleName || "Specialist"}</td>
      </tr>
      <tr>
        <td style="color: #475569; padding: 4px 0;">Experience Level Tier:</td>
        <td style="font-weight: bold; padding: 4px 0;">${(analysis.detectedLevel || "experienced").toUpperCase()}</td>
      </tr>
      <tr>
        <td style="color: #475569; padding: 4px 0;">Standard Mapped:</td>
        <td style="font-weight: bold; padding: 4px 0;">UN SDG 8 for Decent Work & Placement</td>
      </tr>
      <tr>
        <td style="color: #475569; padding: 4px 0;">Assessment Verified Date:</td>
        <td style="font-weight: bold; padding: 4px 0;">${assessmentDate}</td>
      </tr>
    </table>

    <!-- 1. EXECUTIVE SUMMARY & INTEL -->
    <h2 class="section-title">1. Executive Summary & Narrative Intel</h2>
    
    <h3 class="sub-title">1.1 Recruiter Positioning Assessment</h3>
    <p>${analysis.recruiterPerception || "Analytical feedback generated under modern workplace expectations."}</p>

    <h3 class="sub-title">1.2 Professional Perception Gap</h3>
    <div class="card-box" style="border-left: 4px solid #4f46e5;">
      <p><strong>Narrative Perception Gaps:</strong> ${analysis.perceptionGap || "Linguistic passive wording lowers recruiter readiness ratings."}</p>
    </div>
    <p><strong>Visibility Outlook:</strong> ${analysis.opportunityReadinessInsight || "Quantifying deliverables unlocks placement success."}</p>

    <!-- 2. ATS ANALYSIS -->
    <h2 class="section-title">2. ATS Readability & Keywords Alignment</h2>
    <p>Overall Placement Scannability Factor: <strong>${analysis.atsScore}%</strong></p>
    
    <h3 class="sub-title">2.1 Outstanding Narrative Strengths</h3>
    <ul class="bullet-list">
      ${(analysis.strengths || []).map(s => `<li>${s}</li>`).join("")}
    </ul>

    <h3 class="sub-title">2.2 Targeted Developmental Recommendations</h3>
    <ul class="bullet-list">
      ${(analysis.weaknesses || []).map(w => `<li>${w}</li>`).join("")}
    </ul>

    <!-- 3. CAREER MAP -->
    <h2 class="section-title">3. Career Direction Compatibility Match</h2>
    <p>Mapped directions compatibility with key industrial sectors:</p>
    <ul class="bullet-list">
      ${(analysis.careerMap || [
        { sector: "Commercial Engineering Hub", score: 85 },
        { sector: "Systems Management Core", score: 79 }
      ]).map(p => `<li><strong>${p.sector}</strong> — Compatibility Coefficient: <strong>${p.score}%</strong></li>`).join("")}
    </ul>

    <!-- 4. RESUME REWRITE SHEET -->
    <h2 class="section-title">4. Resume Headline Story Rewrite</h2>
    
    <h3 class="sub-title">4.1 Polished Executive Statement Summary</h3>
    <div class="card-box">
      <p style="font-style: italic; margin: 0;">"${analysis.rewrittenBio}"</p>
    </div>

    <h3 class="sub-title">4.2 Quantified Outcomes Resume Bullet Examples</h3>
    <ul class="bullet-list">
      ${bulletPoints.map(b => `<li>${b}</li>`).join("")}
    </ul>

    <!-- 5. GROWTH ROADMAP -->
    <h2 class="section-title">5. Actions Growth Roadmap (SDG 8 Targets)</h2>
    <p>Sequential developmental goals customized for ${candidateName}:</p>
    <ol style="padding-left: 20px;">
      ${(analysis.opportunitySuggestions || [
        "Include metrics details on resume.",
        "Update portfolio workflows."
      ]).map((step, idx) => `<li style="margin-bottom: 8px;"><strong>Phase ${idx + 1}:</strong> ${step}</li>`).join("")}
    </ol>

    <!-- 6. INTERVIEW PERFORMANCE MOCKS (IF ANY ANSWERED) -->
    ${questions.some(q => interviewAnswers[q.id]) ? `
      <h2 class="section-title">6. Mock Interview Intelligence Diagnostics</h2>
      <p>Dissection of practice timeline evaluations:</p>
      ${questions.map((q, idx) => {
        const isAnswered = !!interviewAnswers[q.id];
        if (!isAnswered) return "";
        const evaluation = interviewResults[q.id];
        return `
          <div style="margin-bottom: 18px; padding-bottom: 12px; border-bottom: 1px solid #e2e8f0;">
            <p><strong>Q${idx + 1}: ${q.question}</strong> ${evaluation ? `[Score: ${evaluation.score}%]` : ""}</p>
            <p style="color: #475569; font-style: italic; margin-left: 10px;">"Your answer: ${interviewAnswers[q.id]}"</p>
            ${evaluation ? `<p style="color: #4f46e5; margin-left: 10px;"><strong>Mentorship feedback:</strong> ${evaluation.feedback}</p>` : ""}
            ${evaluation?.refinedAnswer ? `<p style="color: #0f172a; margin-left: 10px;"><strong>Refined Model:</strong> "${evaluation.refinedAnswer}"</p>` : ""}
          </div>
        `;
      }).join("")}
    ` : ""}

    <!-- FOOTER SIGN-OFF -->
    <div class="footer-sign-off">
      <p>Generated by PersonaIQ • Mapped Compliant with UN SDG-8 for Decent Work</p>
      <p>&copy; ${new Date().getFullYear()} PersonaIQ Inc. All analysis coordinates are held private and protected.</p>
    </div>

  </body>
  </html>
  `;

  // Standard Word document trigger Blob
  const blob = new Blob(["\ufeff" + htmlDoc], { type: "application/msword" });
  const docURL = URL.createObjectURL(blob);
  const triggerLink = document.createElement("a");
  triggerLink.href = docURL;
  triggerLink.download = `PersonaIQ_Employability_Report_${candidateName.replace(/\s+/g, "_")}.doc`;
  document.body.appendChild(triggerLink);
  triggerLink.click();
  document.body.removeChild(triggerLink);
}
